name: Create release

on:
  push:
    branches:
      - main
      - v[0-9]*
    paths-ignore:
      - .github/**

permissions:
  contents: write

env:
  GIT_USER_NAME: Fra Bot
  GIT_USER_EMAIL: fragoibot@gmail.com
  V_MAJOR: 1
  V_MINOR: 0

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      major_branch: ${{ steps.majorBranch.outputs.branch }}
    env:
      NEW_VERSION:
    steps:
      - uses: actions/checkout@v6
      - uses: fragoi/bash-actions@v2

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          createRelease

      - name: Export version
        run: |
          exportSharedVars NEW_VERSION

      - name: Ensure branch
        if: ${{ env.NEW_VERSION }}
        id: majorBranch
        run: |
          branch=v${NEW_VERSION%.*}
          ensureBranch $branch
          output branch=$branch

  merge-to-major:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.major_branch && github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.release.outputs.major_branch }}
      - uses: fragoi/bash-actions@v2
      - name: Update major branch
        run: |
          updateBranch main
